### ISSUE TITLE
run.pyやcheck.pyの実行時にエラーが出てします。

### ISSUE THREAD

**Issue by tobieneko** [Hiroshiba/realtime-voice-conversion#5]
check.pyやrun.pyを実行した際に
OSError: /usr/local/lib/python3.6/dist-packages/world4py/libworld.so: cannot open shared object file: No such file or directory
と出力され、動作できない状態となっています。
（ファイルを探してみたところ、上記の階層にちゃんと存在していました。
　※os.path.exists(_WORLD_LIBRARY_PATH)でチェックし　True　が返ることを確認しました。）

realtime-yukarinが推奨環境がWindowsなのは存じておりますが、
become-yukarinでも同様に発生しているため、こちらに書かせていただきました。

解決方法などご存知でしたらご共有いただけると大変助かります。

OS：Ubuntu　18.04.5 LTS (Bionic Beaver)
Python 3.6.9

エラー全文
----------------------------------------------------
python3 check.py --input_path 'input.wav' --input_time_length 5 --output_path 'output.wav' --input_statistics_path './sample/input_statistics.npy' --target_statistics_path './sample/target_statistics.npy' --stage1_model_path './sample/model_stage1/predictor_260000.npz' --stage1_config_path './sample/model_stage1/config.json' --stage2_model_path './sample/model_stage2/predictor_8000.npz' --stage2_config_path './sample/model_stage2/config.json'
Traceback (most recent call last):
  File "check.py", line 13, in <module>
    from realtime_voice_conversion.config import VocodeMode
  File "/home/＊＊＊＊/ドキュメント/IkeboMaster/realtime-yukarin/realtime_voice_conversion/__init__.py", line 1, in <module>
    from . import stream
  File "/home/＊＊＊＊/ドキュメント/IkeboMaster/realtime-yukarin/realtime_voice_conversion/stream/__init__.py", line 2, in <module>
    from .decode_stream import DecodeStream
  File "/home/＊＊＊＊/ドキュメント/IkeboMaster/realtime-yukarin/realtime_voice_conversion/stream/decode_stream.py", line 7, in <module>
    from ..yukarin_wrapper.vocoder import Vocoder
  File "/home/＊＊＊＊/ドキュメント/IkeboMaster/realtime-yukarin/realtime_voice_conversion/yukarin_wrapper/vocoder.py", line 5, in <module>
    from world4py.native import structures, apidefinitions, utils
  File "/usr/local/lib/python3.6/dist-packages/world4py/native/__init__.py", line 6, in <module>
    from world4py.native import apis, tools, utils, structures
  File "/usr/local/lib/python3.6/dist-packages/world4py/native/apis.py", line 6, in <module>
    from world4py.native import apidefinitions, structures, utils
  File "/usr/local/lib/python3.6/dist-packages/world4py/native/apidefinitions.py", line 7, in <module>
    from world4py.native import structures, instance
  File "/usr/local/lib/python3.6/dist-packages/world4py/native/instance.py", line 9, in <module>
    _WORLD = ctypes.cdll.LoadLibrary(_WORLD_LIBRARY_PATH)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.6/dist-packages/world4py/libworld.so: cannot open shared object file: No such file or directory

**Comment by tobieneko** [comment]
補足です。
過去のissueの中で再インストールをおすすめされているものもあったため
sudo pip3 uninstall world4py
sudo pip3 --no-cache-dir install -I world4py
の流れで再インストールを試しましたが、現象は同じでした。

**Comment by tobieneko** [comment]
補足です。
過去のissueの中で再インストールをおすすめされているものもあったため
sudo pip3 uninstall world4py
sudo pip3 --no-cache-dir install -I world4py
の流れで再インストールを試しましたが、現象は同じでした。
